import {
  Machine,
  Tank,
  StockConsumable,
  Order,
  Customer,
  SupportTicket,
  Coupon,
  AppBanner,
  PushNotification,
  AdSpaceBooking,
  AuditLogItem,
  RolePermission,
  UserRole,
} from './types';

export const ROLE_PERMISSIONS: Record<UserRole, RolePermission> = {
  owner: {
    role: 'owner',
    label: 'Chief Owner (Full Root)',
    badgeClass: 'bg-brand-50 text-brand-700 border-brand-200',
    allowedModules: ['dashboard', 'machines', 'orders', 'customers', 'inventory', 'analytics', 'marketing', 'support', 'settings', 'architecture'],
    canMutateHardware: true,
    canMutateMachines: true,
    canApproveRefunds: true,
    canAccessFinances: true,
    canAccessMarketing: true,
    canAccessSecurity: true,
    canResolveDisputes: true,
    canCreditWallet: true,
  },
  ops: {
    role: 'ops',
    label: 'Operations Lead',
    badgeClass: 'bg-leaf-50 text-leaf-700 border-leaf-200',
    allowedModules: ['dashboard', 'machines', 'orders', 'inventory', 'analytics', 'support', 'settings', 'architecture'],
    canMutateHardware: false,
    canMutateMachines: true,
    canApproveRefunds: true,
    canAccessFinances: false,
    canAccessMarketing: false,
    canAccessSecurity: false,
    canResolveDisputes: true,
    canCreditWallet: false,
  },
  support: {
    role: 'support',
    label: 'Support Desk Agent',
    badgeClass: 'bg-amber2-50 text-amber2-700 border-amber2-200',
    allowedModules: ['dashboard', 'machines', 'orders', 'customers', 'support', 'architecture'],
    canMutateHardware: false,
    canMutateMachines: false,
    canApproveRefunds: false, // Per specification: Support can resolve and request refund, but payout approval requires ops/finance
    canAccessFinances: false,
    canAccessMarketing: false,
    canAccessSecurity: false,
    canResolveDisputes: true,
    canCreditWallet: false,
  },
  finance: {
    role: 'finance',
    label: 'Finance & Accounts',
    badgeClass: 'bg-blue-50 text-blue-700 border-blue-200',
    allowedModules: ['dashboard', 'machines', 'orders', 'customers', 'inventory', 'analytics', 'marketing', 'support', 'architecture'],
    canMutateHardware: false,
    canMutateMachines: false,
    canApproveRefunds: true,
    canAccessFinances: true,
    canAccessMarketing: false,
    canAccessSecurity: false,
    canResolveDisputes: true,
    canCreditWallet: true,
  },
  marketing: {
    role: 'marketing',
    label: 'Growth & Campaigns',
    badgeClass: 'bg-purple-50 text-purple-700 border-purple-200',
    allowedModules: ['dashboard', 'customers', 'analytics', 'marketing', 'architecture'],
    canMutateHardware: false,
    canMutateMachines: false,
    canApproveRefunds: false,
    canAccessFinances: false,
    canAccessMarketing: true,
    canAccessSecurity: false,
    canResolveDisputes: false,
    canCreditWallet: false,
  },
  viewer: {
    role: 'viewer',
    label: 'Read-Only Viewer',
    badgeClass: 'bg-gray-100 text-ink-700 border-gray-200',
    allowedModules: ['dashboard', 'machines', 'orders', 'inventory', 'analytics', 'architecture'],
    canMutateHardware: false,
    canMutateMachines: false,
    canApproveRefunds: false,
    canAccessFinances: false,
    canAccessMarketing: false,
    canAccessSecurity: false,
    canResolveDisputes: false,
    canCreditWallet: false,
  },
};

export const INITIAL_MACHINES: Machine[] = [
  {
    id: 'MCH-001',
    name: 'Campus Hub',
    code: 'MCH-001',
    city: 'Mumbai',
    location: 'IIT Campus, Cafeteria Quad A',
    status: 'ONLINE',
    mode: 'HOT',
    temp: 65.4,
    targetTemp: 66.0,
    milkLiters: 38,
    maxMilkLiters: 45,
    cupsCount: 142,
    kitsCount: 168,
    signalDbm: -68,
    lastSeen: 'just now',
    isLocked: false,
    sdCardFreeMb: 24800,
    firmwareVersion: 'v2.4.1-rc3',
    firmwareChecksum: '9a4c8e71b2f09d8e',
    bootCount: 14,
    wdtResets: 0,
    camera1Online: true,
    camera2Online: true,
    activeFaults: [],
  },
  {
    id: 'MCH-002',
    name: 'Mall Lane',
    code: 'MCH-002',
    city: 'Mumbai',
    location: 'Phoenix Palladium, Ground Concourse',
    status: 'ONLINE',
    mode: 'COLD',
    temp: 6.2,
    targetTemp: 6.0,
    milkLiters: 21,
    maxMilkLiters: 45,
    cupsCount: 88,
    kitsCount: 94,
    signalDbm: -74,
    lastSeen: '12s ago',
    isLocked: false,
    sdCardFreeMb: 18400,
    firmwareVersion: 'v2.4.1-rc3',
    firmwareChecksum: '9a4c8e71b2f09d8e',
    bootCount: 22,
    wdtResets: 1,
    camera1Online: true,
    camera2Online: true,
    activeFaults: ['LOW_MILK_BUFFER'],
  },
  {
    id: 'MCH-003',
    name: 'Tech Park Central',
    code: 'MCH-003',
    city: 'Pune',
    location: 'CyberCity Wing 4, Lobby B',
    status: 'ONLINE',
    mode: 'HOT',
    temp: 63.8,
    targetTemp: 65.0,
    milkLiters: 42,
    maxMilkLiters: 45,
    cupsCount: 195,
    kitsCount: 210,
    signalDbm: -62,
    lastSeen: '45s ago',
    isLocked: false,
    sdCardFreeMb: 29100,
    firmwareVersion: 'v2.4.0',
    firmwareChecksum: '3c8f12aa9e8401df',
    bootCount: 6,
    wdtResets: 0,
    camera1Online: true,
    camera2Online: true,
    activeFaults: [],
  },
];

export const INITIAL_TANKS: Tank[] = [
  {
    id: 'TNK-901',
    machineId: 'MCH-001',
    tankUid: 'FSSAI-MH-2026-901',
    liters: 38,
    maxLiters: 45,
    filledAt: 'Today, 04:30 AM',
    expiresAt: 'Today, 10:30 PM',
    status: 'ACTIVE',
    ageHours: 6.5,
  },
  {
    id: 'TNK-884',
    machineId: 'MCH-002',
    tankUid: 'FSSAI-MH-2026-884',
    liters: 21,
    maxLiters: 45,
    filledAt: 'Today, 03:15 AM',
    expiresAt: 'Today, 09:15 PM',
    status: 'ACTIVE',
    ageHours: 7.8,
  },
  {
    id: 'TNK-752',
    machineId: 'MCH-001',
    tankUid: 'FSSAI-MH-2026-752',
    liters: 0,
    maxLiters: 45,
    filledAt: 'Yesterday, 04:00 AM',
    expiresAt: 'Yesterday, 10:00 PM',
    status: 'DISPOSED',
    disposalReason: 'Shift complete, cycle drained',
    ageHours: 18,
  },
];

export const INITIAL_STOCK: StockConsumable[] = [
  {
    id: 'STK-001-A',
    machineId: 'MCH-001',
    variantId: 'V1',
    variantName: 'Manhattan Velvet Cappuccino',
    quantity: 82,
    maxCapacity: 120,
    reorderThreshold: 25,
    lastRefillAt: 'Yesterday, 10:00 PM',
    lastRefillBy: 'Tech Suresh K.',
  },
  {
    id: 'STK-001-B',
    machineId: 'MCH-001',
    variantId: 'V2',
    variantName: 'Classic Café Latte',
    quantity: 44,
    maxCapacity: 80,
    reorderThreshold: 20,
    lastRefillAt: 'Yesterday, 10:00 PM',
    lastRefillBy: 'Tech Suresh K.',
  },
  {
    id: 'STK-001-C',
    machineId: 'MCH-001',
    variantId: 'V3',
    variantName: 'Grande Roast',
    quantity: 36,
    maxCapacity: 60,
    reorderThreshold: 15,
    lastRefillAt: 'Yesterday, 10:00 PM',
    lastRefillBy: 'Tech Suresh K.',
  },
  {
    id: 'STK-001-D',
    machineId: 'MCH-001',
    variantId: 'V4',
    variantName: 'Chilled Manhattan Frappe',
    quantity: 28,
    maxCapacity: 50,
    reorderThreshold: 12,
    lastRefillAt: 'Yesterday, 10:00 PM',
    lastRefillBy: 'Tech Suresh K.',
  },
  {
    id: 'STK-002-A',
    machineId: 'MCH-002',
    variantId: 'V4',
    variantName: 'Chilled Manhattan Frappe',
    quantity: 14,
    maxCapacity: 80,
    reorderThreshold: 20,
    lastRefillAt: 'Today, 03:20 AM',
    lastRefillBy: 'Tech Imran S.',
  },
  {
    id: 'STK-002-B',
    machineId: 'MCH-002',
    variantId: 'V1',
    variantName: 'Manhattan Velvet Cappuccino',
    quantity: 45,
    maxCapacity: 100,
    reorderThreshold: 20,
    lastRefillAt: 'Today, 03:20 AM',
    lastRefillBy: 'Tech Imran S.',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-9842',
    orderNo: '#ORD-9842',
    time: '11:42 AM',
    machineId: 'MCH-001',
    machineName: 'Campus Hub',
    variant: 'Manhattan Velvet Cappuccino',
    amount: 50,
    discount: 0,
    netAmount: 50,
    costBasis: 18.2,
    paymentMethod: 'UPI',
    status: 'Completed',
    isFlagged: true,
    utr: 'UPI/20261001/9842011245',
    buyerName: 'Aman Sharma',
    buyerPhone: '+91 98201 •••••',
    buyerId: 'CUS-401',
    qrSource: 'Purchase',
    qrShareCount: 0,
    qrExpiry: '01 Oct 2026, 12:42 PM',
    tankUid: 'FSSAI-MH-2026-901',
    tankAgeHours: 7.2,
    hasDispute: true,
    disputeTicketId: 'TKT-8902',
    dispenseLog: {
      valveOpenMs: 2100,
      flowPulses: 14,
      expectedMl: 180,
      dispensedMl: 147,
      variancePct: 18.3,
      cupDetected: true,
      kitDropped: true,
      malaiPumpMs: 820,
      conveyorSteps: 450,
      windowOpened: true,
      pickupDetected: false,
    },
  },
  {
    id: 'ORD-9841',
    orderNo: '#ORD-9841',
    time: '11:38 AM',
    machineId: 'MCH-001',
    machineName: 'Campus Hub',
    variant: 'Classic Café Latte',
    amount: 20,
    discount: 0,
    netAmount: 20,
    costBasis: 8.5,
    paymentMethod: 'Wallet',
    status: 'Completed',
    isFlagged: false,
    utr: 'WLT/88392110',
    buyerName: 'Pooja Iyer',
    buyerPhone: '+91 97112 •••••',
    buyerId: 'CUS-402',
    qrSource: 'Purchase',
    qrShareCount: 0,
    qrExpiry: '01 Oct 2026, 12:38 PM',
    tankUid: 'FSSAI-MH-2026-901',
    tankAgeHours: 7.1,
    hasDispute: false,
    dispenseLog: {
      valveOpenMs: 2500,
      flowPulses: 18,
      expectedMl: 180,
      dispensedMl: 178,
      variancePct: 1.1,
      cupDetected: true,
      kitDropped: true,
      malaiPumpMs: 0,
      conveyorSteps: 450,
      windowOpened: true,
      pickupDetected: true,
    },
  },
  {
    id: 'ORD-9840',
    orderNo: '#ORD-9840',
    time: '11:29 AM',
    machineId: 'MCH-002',
    machineName: 'Mall Lane',
    variant: 'Chilled Manhattan Frappe',
    amount: 45,
    discount: 5,
    netAmount: 40,
    costBasis: 16.0,
    paymentMethod: 'UPI',
    status: 'Completed',
    isFlagged: false,
    utr: 'UPI/20261001/4491028371',
    buyerName: 'Vikram Seth',
    buyerPhone: '+91 98334 •••••',
    buyerId: 'CUS-403',
    qrSource: 'Ad Reward',
    qrShareCount: 1,
    qrExpiry: '01 Oct 2026, 12:29 PM',
    tankUid: 'FSSAI-MH-2026-884',
    tankAgeHours: 8.2,
    hasDispute: false,
    dispenseLog: {
      valveOpenMs: 2800,
      flowPulses: 22,
      expectedMl: 220,
      dispensedMl: 218,
      variancePct: 0.9,
      cupDetected: true,
      kitDropped: true,
      malaiPumpMs: 600,
      conveyorSteps: 450,
      windowOpened: true,
      pickupDetected: true,
    },
  },
  {
    id: 'ORD-9839',
    orderNo: '#ORD-9839',
    time: '11:15 AM',
    machineId: 'MCH-001',
    machineName: 'Campus Hub',
    variant: 'Manhattan Velvet Cappuccino',
    amount: 50,
    discount: 0,
    netAmount: 50,
    costBasis: 18.2,
    paymentMethod: 'Coins',
    status: 'Completed',
    isFlagged: false,
    utr: 'CNS/COIN-7729',
    buyerName: 'Rohan Mehra',
    buyerPhone: '+91 98210 •••••',
    buyerId: 'CUS-404',
    qrSource: 'Referral',
    qrShareCount: 0,
    qrExpiry: '01 Oct 2026, 12:15 PM',
    tankUid: 'FSSAI-MH-2026-901',
    tankAgeHours: 6.7,
    hasDispute: false,
    dispenseLog: {
      valveOpenMs: 2520,
      flowPulses: 18,
      expectedMl: 180,
      dispensedMl: 179,
      variancePct: 0.5,
      cupDetected: true,
      kitDropped: true,
      malaiPumpMs: 820,
      conveyorSteps: 450,
      windowOpened: true,
      pickupDetected: true,
    },
  },
  {
    id: 'ORD-9838',
    orderNo: '#ORD-9838',
    time: '10:55 AM',
    machineId: 'MCH-002',
    machineName: 'Mall Lane',
    variant: 'Grande Roast',
    amount: 30,
    discount: 0,
    netAmount: 30,
    costBasis: 11.0,
    paymentMethod: 'UPI',
    status: 'Preparing',
    isFlagged: false,
    utr: 'UPI/20261001/1092837461',
    buyerName: 'Neha Deshmukh',
    buyerPhone: '+91 99302 •••••',
    buyerId: 'CUS-405',
    qrSource: 'Purchase',
    qrShareCount: 0,
    qrExpiry: '01 Oct 2026, 11:55 AM',
    tankUid: 'FSSAI-MH-2026-884',
    tankAgeHours: 7.6,
    hasDispute: false,
    dispenseLog: {
      valveOpenMs: 1400,
      flowPulses: 10,
      expectedMl: 180,
      dispensedMl: 100,
      variancePct: 0.0,
      cupDetected: true,
      kitDropped: true,
      malaiPumpMs: 0,
      conveyorSteps: 220,
      windowOpened: false,
      pickupDetected: false,
    },
  },
  {
    id: 'ORD-9837',
    orderNo: '#ORD-9837',
    time: '10:30 AM',
    machineId: 'MCH-001',
    machineName: 'Campus Hub',
    variant: 'Manhattan Velvet Cappuccino',
    amount: 50,
    discount: 0,
    netAmount: 50,
    costBasis: 18.2,
    paymentMethod: 'UPI',
    status: 'Cancelled',
    isFlagged: true,
    utr: 'UPI/20261001/9920192831',
    buyerName: 'Kunal Verma',
    buyerPhone: '+91 98205 •••••',
    buyerId: 'CUS-406',
    qrSource: 'Purchase',
    qrShareCount: 0,
    qrExpiry: '01 Oct 2026, 11:30 AM',
    tankUid: 'FSSAI-MH-2026-901',
    tankAgeHours: 6.0,
    hasDispute: true,
    disputeTicketId: 'TKT-8899',
    dispenseLog: {
      valveOpenMs: 0,
      flowPulses: 0,
      expectedMl: 180,
      dispensedMl: 0,
      variancePct: 100.0,
      cupDetected: false,
      kitDropped: false,
      malaiPumpMs: 0,
      conveyorSteps: 0,
      windowOpened: false,
      pickupDetected: false,
    },
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'CUS-401',
    name: 'Aman Sharma',
    phone: '+91 98201 44820',
    avatar: 'AS',
    ordersCount: 38,
    totalSpend: 1780,
    lastOrder: 'Today, 11:42 AM',
    walletBalance: 240,
    coins: 350,
    streak: 12,
    longestStreak: 21,
    favoriteVariant: 'Manhattan Velvet Cappuccino',
    segment: 'High Value',
    leaderboardOptIn: true,
    city: 'Mumbai',
    collegeOrWork: 'IIT Bombay, Dept of CS',
    isBlocked: false,
  },
  {
    id: 'CUS-402',
    name: 'Pooja Iyer',
    phone: '+91 97112 99014',
    avatar: 'PI',
    ordersCount: 22,
    totalSpend: 840,
    lastOrder: 'Today, 11:38 AM',
    walletBalance: 120,
    coins: 180,
    streak: 5,
    longestStreak: 14,
    favoriteVariant: 'Classic Café Latte',
    segment: 'Active Today',
    leaderboardOptIn: true,
    city: 'Mumbai',
    collegeOrWork: 'Powai Tech Park',
    isBlocked: false,
  },
  {
    id: 'CUS-403',
    name: 'Vikram Seth',
    phone: '+91 98334 11209',
    avatar: 'VS',
    ordersCount: 17,
    totalSpend: 720,
    lastOrder: 'Today, 11:29 AM',
    walletBalance: 80,
    coins: 410,
    streak: 3,
    longestStreak: 9,
    favoriteVariant: 'Chilled Manhattan Frappe',
    segment: 'Active Today',
    leaderboardOptIn: false,
    city: 'Mumbai',
    collegeOrWork: 'Morgan Stanley',
    isBlocked: false,
  },
  {
    id: 'CUS-404',
    name: 'Rohan Mehra',
    phone: '+91 98210 77391',
    avatar: 'RM',
    ordersCount: 45,
    totalSpend: 2250,
    lastOrder: 'Today, 11:15 AM',
    walletBalance: 560,
    coins: 620,
    streak: 18,
    longestStreak: 28,
    favoriteVariant: 'Manhattan Velvet Cappuccino',
    segment: 'High Value',
    leaderboardOptIn: true,
    city: 'Mumbai',
    collegeOrWork: 'Hiranandani Towers',
    isBlocked: false,
  },
];

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'TKT-8902',
    ticketNo: 'TKT-8902',
    orderId: 'ORD-9842',
    orderNo: '#ORD-9842',
    customerId: 'CUS-401',
    customerName: 'Aman Sharma',
    customerPhone: '+91 98201 44820',
    machineId: 'MCH-001',
    machineName: 'Campus Hub',
    claimedAt: 'Today, 11:45 AM (8m ago)',
    amount: 50,
    utr: 'UPI/20261001/9842011245',
    reason: 'cup_stuck',
    reasonLabel: 'Cup stuck in chute & incomplete pour',
    status: 'OPEN',
    priority: 'HIGH',
    slaRemainingMinutes: 4,
    channel: 'Bot',
    customerMessage: 'I scanned the QR code, cup got stuck slightly tilted and only half coffee poured. The shutter closed before I could grab it properly. Please refund.',
    dispenseVariance: 18.3,
  },
  {
    id: 'TKT-8899',
    ticketNo: 'TKT-8899',
    orderId: 'ORD-9837',
    orderNo: '#ORD-9837',
    customerId: 'CUS-406',
    customerName: 'Kunal Verma',
    customerPhone: '+91 98205 99201',
    machineId: 'MCH-001',
    machineName: 'Campus Hub',
    claimedAt: 'Today, 10:35 AM (1h 18m ago)',
    amount: 50,
    utr: 'UPI/20261001/9920192831',
    reason: 'no_coffee',
    reasonLabel: 'Payment deducted but no dispense initiated',
    status: 'RESOLVED_REFUND',
    priority: 'HIGH',
    slaRemainingMinutes: 0,
    channel: 'WhatsApp',
    customerMessage: 'Money cut from GPay, machine displayed timeout error. No coffee given.',
    dispenseVariance: 100.0,
    resolution: 'Confirmed 0 pulses and shutter remained locked. Full refund of ₹50 initiated to UPI source.',
    resolvedAt: 'Today, 10:48 AM',
    resolvedBy: 'Admin Rohan',
  },
  {
    id: 'TKT-8890',
    ticketNo: 'TKT-8890',
    orderId: 'ORD-9812',
    orderNo: '#ORD-9812',
    customerId: 'CUS-402',
    customerName: 'Pooja Iyer',
    customerPhone: '+91 97112 99014',
    machineId: 'MCH-002',
    machineName: 'Mall Lane',
    claimedAt: 'Yesterday, 06:12 PM',
    amount: 20,
    utr: 'WLT/88392110',
    reason: 'no_kit',
    reasonLabel: 'Sugar & stirrer kit did not drop',
    status: 'RESOLVED_REFUND',
    priority: 'LOW',
    slaRemainingMinutes: 0,
    channel: 'Bot',
    customerMessage: 'Coffee was good but no kit dispenser triggered for sweetener.',
    dispenseVariance: 1.2,
    resolution: 'Verified solenoid jam on kit rack 2. Compensated ₹20 wallet bonus credit.',
    resolvedAt: 'Yesterday, 06:25 PM',
    resolvedBy: 'Tech Imran S.',
  },
  {
    id: 'TKT-8874',
    ticketNo: 'TKT-8874',
    orderId: 'ORD-9755',
    orderNo: '#ORD-9755',
    customerId: 'CUS-409',
    customerName: 'Devika Pillai',
    customerPhone: '+91 99204 88310',
    machineId: 'MCH-001',
    machineName: 'Campus Hub',
    claimedAt: 'Yesterday, 02:40 PM',
    amount: 50,
    utr: 'UPI/20260930/11992019',
    reason: 'spill',
    reasonLabel: 'Claimed heavy spillage on pickup',
    status: 'RESOLVED_REJECTED',
    priority: 'MEDIUM',
    slaRemainingMinutes: 0,
    channel: 'Manual',
    customerMessage: 'Cup fell over as soon as window opened.',
    dispenseVariance: 2.1,
    resolution: 'Camera clip at 14:41:05 shows customer pulled cup sideways before window fully opened. Dispense executed nominal at 181ml. Rejected with video clip proof link sent via SMS.',
    resolvedAt: 'Yesterday, 03:02 PM',
    resolvedBy: 'Chief Rohan',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'CPN-1',
    code: 'CAMPUSLOVE',
    title: 'Student Welcome ₹15 Off',
    type: 'FLAT',
    value: 15,
    minOrder: 30,
    usageCount: 142,
    maxUsage: 500,
    budgetCap: 7500,
    budgetBurned: 2130,
    expiresAt: '15 Oct 2026',
    status: 'ACTIVE',
  },
  {
    id: 'CPN-2',
    code: 'VELVET20',
    title: 'Manhattan Velvet 20% Special',
    type: 'PERCENT',
    value: 20,
    minOrder: 40,
    usageCount: 88,
    maxUsage: 300,
    budgetCap: 3000,
    budgetBurned: 880,
    expiresAt: '10 Oct 2026',
    status: 'ACTIVE',
  },
  {
    id: 'CPN-3',
    code: 'FESTIVALFREE',
    title: 'Diwali Prep Free Classic Latte',
    type: 'FREE_ITEM',
    value: 20,
    minOrder: 50,
    usageCount: 45,
    maxUsage: 100,
    budgetCap: 2000,
    budgetBurned: 900,
    expiresAt: '25 Oct 2026',
    status: 'ACTIVE',
  },
];

export const INITIAL_BANNERS: AppBanner[] = [
  {
    id: 'BAN-1',
    title: 'Manhattan Velvet Crown Roast — Handcrafted Perfection',
    placement: 'Home Carousel',
    impressions: 4820,
    clicks: 642,
    priority: 1,
    status: 'ACTIVE',
    previewColor: '#F04E23',
  },
  {
    id: 'BAN-2',
    title: 'Chill with Frappe at Mall Lane — Cool off now!',
    placement: 'Home Carousel',
    impressions: 2150,
    clicks: 295,
    priority: 2,
    status: 'ACTIVE',
    previewColor: '#CA8A04',
  },
  {
    id: 'BAN-3',
    title: 'Refer a Colleague & Earn ₹50 Coffee Float',
    placement: 'Wallet Screen',
    impressions: 1890,
    clicks: 310,
    priority: 1,
    status: 'ACTIVE',
    previewColor: '#16A34A',
  },
];

export const INITIAL_PUSH_NOTIFICATIONS: PushNotification[] = [
  {
    id: 'PSH-1',
    title: '☕ Hot Velvet Cappuccino brewing at Campus Quad!',
    body: 'Fresh morning batch mounted. Skip the campus canteen rush.',
    targetSegment: 'Active Today',
    sentAt: 'Today, 08:30 AM',
    delivered: 1480,
    opened: 640,
    openRate: 43.2,
  },
  {
    id: 'PSH-2',
    title: '⚡ Your 5-day streak is burning! Don’t lose your badge',
    body: 'Grab a cup at Mall Lane or Campus Hub before 2 PM.',
    targetSegment: 'Lapsed 3d',
    sentAt: 'Yesterday, 11:00 AM',
    delivered: 420,
    opened: 185,
    openRate: 44.0,
  },
];

export const INITIAL_AD_SPACES: AdSpaceBooking[] = [
  {
    id: 'ADS-1',
    machineId: 'MCH-001',
    machineName: 'Campus Hub',
    slotName: 'Side Panel',
    advertiser: 'Fintech App - CredFlow',
    rateMonthly: 8500,
    monthsBooked: 3,
    status: 'PAID',
    renewalDate: '28 Oct 2026',
  },
  {
    id: 'ADS-2',
    machineId: 'MCH-002',
    machineName: 'Mall Lane',
    slotName: 'Idle Display',
    advertiser: 'Urban Beats Headphones',
    rateMonthly: 6200,
    monthsBooked: 2,
    status: 'PAID',
    renewalDate: '14 Nov 2026',
  },
  {
    id: 'ADS-3',
    machineId: 'MCH-001',
    machineName: 'Campus Hub',
    slotName: 'Cup Print',
    advertiser: 'Hackathon 2026 Sponsor',
    rateMonthly: 4500,
    monthsBooked: 1,
    status: 'OVERDUE',
    renewalDate: '02 Oct 2026',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'AUD-901',
    timestamp: 'Today, 11:46 AM',
    adminName: 'Chief Rohan',
    role: 'owner',
    action: 'DISPUTE_CLAIMED',
    target: 'Ticket TKT-8902 (#ORD-9842)',
    details: 'Opened dispute desk to inspect synchronized 30s camera clip & telemetry.',
  },
  {
    id: 'AUD-900',
    timestamp: 'Today, 10:48 AM',
    adminName: 'Chief Rohan',
    role: 'owner',
    action: 'REFUND_APPROVED',
    target: 'Order #ORD-9837 (₹50)',
    details: 'Approved ₹50 refund to UPI source due to zero-dispense timeout.',
  },
  {
    id: 'AUD-899',
    timestamp: 'Today, 04:30 AM',
    adminName: 'Tech Suresh K.',
    role: 'ops',
    action: 'TANK_MOUNTED',
    target: 'Machine MCH-001',
    details: 'Mounted 38L fresh batch TNK-901 with FSSAI-MH-2026-901 certification.',
  },
  {
    id: 'AUD-898',
    timestamp: 'Yesterday, 09:15 PM',
    adminName: 'Chief Rohan',
    role: 'owner',
    action: 'CONFIG_UPDATED',
    target: 'Fleet Target Temp',
    details: 'Changed default hot mode temp from 64.0°C to 66.0°C.',
  },
];

export const RANGES_DATA = {
  'Today': {
    labels: ['12 AM', '4 AM', '8 AM', '12 PM', '4 PM', '8 PM', '11 PM'],
    revenue: [490, 650, 810, 1320, 1220, 1550, 760], // sums to 6,800
    orders: [12, 16, 20, 32, 30, 38, 20], // sums to 168
  },
  'This Week': {
    labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    revenue: [18400, 21600, 19800, 26300, 24100, 31200, 16850],
    orders: [52, 61, 55, 74, 68, 88, 44],
  },
  'This Month': {
    labels: ['W1', 'W2', 'W3', 'W4'],
    revenue: [124000, 138000, 131000, 152000],
    orders: [352, 398, 374, 428],
  },
};

export const VARIANTS_BREAKDOWN = [
  { name: 'Manhattan Velvet Cappuccino', short: 'Manhattan Velvet', orders: 93, rev: 4650, pct: 55, color: '#F04E23', emoji: '👑' },
  { name: 'Classic Café Latte', short: 'Classic Latte', orders: 34, rev: 680, pct: 20, color: '#EAB308', emoji: '☕' },
  { name: 'Grande Roast', short: 'Grande Roast', orders: 25, rev: 750, pct: 15, color: '#22C55E', emoji: '🔥' },
  { name: 'Chilled Manhattan Frappe', short: 'Chilled Frappe', orders: 16, rev: 720, pct: 10, color: '#EF4444', emoji: '🧊' },
];

export const STATUS_BREAKDOWN = [
  { name: 'Completed', n: 108, pct: 64, color: '#16A34A' },
  { name: 'Preparing', n: 37, pct: 22, color: '#EAB308' },
  { name: 'Pending', n: 17, pct: 10, color: '#F04E23' },
  { name: 'Cancelled', n: 6, pct: 4, color: '#9CA3AF' },
];
